##############################################
# CENTRALIZED LOGGING
# All bot and user actions logged here
##############################################

import logging
import os
from datetime import datetime
from common.config import (
    LOG_LEVEL, LOG_FORMAT, LOG_DATE_FORMAT
)

##############################################
# GET ABSOLUTE LOG PATHS
##############################################

# Get the project root directory (parent of 'common' folder)
_LOGGER_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_LOGGER_DIR)

LOG_DIR = os.path.join(_PROJECT_ROOT, "logs")
AUDIT_LOG_DIR = os.path.join(_PROJECT_ROOT, "logs", "audit")

##############################################
# ENSURE LOG DIRECTORIES EXIST
##############################################

os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(AUDIT_LOG_DIR, exist_ok=True)

##############################################
# CUSTOM FORMATTERS
##############################################

class LogFormatter(logging.Formatter):
    """Custom formatter with colors for console output."""

    COLORS = {
        'DEBUG': '\033[94m',     # Blue
        'INFO': '\033[92m',      # Green
        'WARNING': '\033[93m',   # Yellow
        'ERROR': '\033[91m',     # Red
        'CRITICAL': '\033[95m',  # Magenta
        'RESET': '\033[0m'       # Reset
    }

    def format(self, record):
        # Add color for console
        if hasattr(self, 'use_color') and self.use_color:
            color = self.COLORS.get(record.levelname, self.COLORS['RESET'])
            record.levelname = f"{color}{record.levelname}{self.COLORS['RESET']}"
        return super().format(record)

##############################################
# LOGGER SETUP
##############################################

def setup_logger(name, log_file=None, level=LOG_LEVEL):
    """
    Create a logger with file and console handlers.

    Args:
        name: Logger name (e.g., 'NIFTYBOT', 'EXECUTOR', 'SYSTEM')
        log_file: Optional specific log file
        level: Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

    Returns:
        Configured logger instance
    """
    logger = logging.getLogger(name)
    logger.setLevel(getattr(logging, level))

    # Prevent duplicate handlers
    if logger.handlers:
        return logger

    # File handler - main trading log
    main_log_path = os.path.join(LOG_DIR, "trading.log")
    file_handler = logging.FileHandler(main_log_path)
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(logging.Formatter(LOG_FORMAT, LOG_DATE_FORMAT))
    logger.addHandler(file_handler)

    # File handler - daily audit log
    today = datetime.now().strftime("%Y-%m-%d")
    audit_log_path = os.path.join(AUDIT_LOG_DIR, f"{today}.log")
    audit_handler = logging.FileHandler(audit_log_path)
    audit_handler.setLevel(logging.DEBUG)
    audit_handler.setFormatter(logging.Formatter(LOG_FORMAT, LOG_DATE_FORMAT))
    logger.addHandler(audit_handler)

    # Console handler with colors
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)
    console_formatter = LogFormatter(LOG_FORMAT, LOG_DATE_FORMAT)
    console_formatter.use_color = True
    console_handler.setFormatter(console_formatter)
    logger.addHandler(console_handler)

    # Optional specific log file
    if log_file:
        specific_handler = logging.FileHandler(os.path.join(LOG_DIR, log_file))
        specific_handler.setLevel(logging.INFO)
        specific_handler.setFormatter(logging.Formatter(LOG_FORMAT, LOG_DATE_FORMAT))
        logger.addHandler(specific_handler)

    return logger

##############################################
# PRE-CONFIGURED LOGGERS
##############################################

# System logger - for application-level events
system_logger = setup_logger("SYSTEM")

# Trade logger - for all trade executions
trade_logger = setup_logger("TRADES", log_file="trades.log")

# Error logger - for errors only
error_logger = setup_logger("ERRORS", log_file="errors.log")

##############################################
# CONVENIENCE FUNCTIONS
##############################################

def log_system(message, level="INFO"):
    """Log system events (bot start/stop, config changes, etc.)"""
    getattr(system_logger, level.lower())(message)

def log_trade(action, symbol, **kwargs):
    """
    Log trade actions with structured data.

    Args:
        action: BUY, SELL, EXIT, MODIFY, CANCEL
        symbol: Trading symbol
        **kwargs: Additional fields (qty, price, order_id, pnl, etc.)
    """
    details = " | ".join([f"{k}: {v}" for k, v in kwargs.items()])
    trade_logger.info(f"{action} | {symbol} | {details}")

def log_signal(bot_name, signal_type, symbol, **kwargs):
    """
    Log trading signals generated by bots.

    Args:
        bot_name: NIFTYBOT, STOCKBOT, etc.
        signal_type: BUY_CE, BUY_PE, BUY, SELL, EXIT
        symbol: Trading symbol
        **kwargs: Additional signal details
    """
    logger = setup_logger(bot_name)
    details = " | ".join([f"{k}: {v}" for k, v in kwargs.items()])
    logger.info(f"Signal: {signal_type} | {symbol} | {details}")

def log_error(source, message, exception=None):
    """Log errors with optional exception details."""
    error_logger.error(f"{source} | {message}")
    if exception:
        error_logger.exception(exception)

def log_user_action(action, details=None):
    """Log user-initiated actions."""
    msg = f"USER ACTION | {action}"
    if details:
        msg += f" | {details}"
    system_logger.info(msg)

def log_position(action, symbol, **kwargs):
    """Log position updates (open, update, close)."""
    details = " | ".join([f"{k}: {v}" for k, v in kwargs.items()])
    trade_logger.info(f"POSITION {action} | {symbol} | {details}")

##############################################
# DAILY SUMMARY
##############################################

def log_daily_summary(trades, winners, losers, total_pnl):
    """Log end-of-day summary."""
    system_logger.info("=" * 50)
    system_logger.info("DAILY SUMMARY")
    system_logger.info("=" * 50)
    system_logger.info(f"Total Trades: {trades}")
    system_logger.info(f"Winners: {winners}")
    system_logger.info(f"Losers: {losers}")
    system_logger.info(f"Win Rate: {(winners/trades*100) if trades > 0 else 0:.1f}%")
    system_logger.info(f"Total P&L: Rs. {total_pnl:,.2f}")
    system_logger.info("=" * 50)
